drop-cms-preview: # preview content
  image: ${DROP_CMS_IMAGE_NAME}
  environment:
    DROPCMS_ROOTDIR: '/preview-content'
    DROPCMS_PUBLISH_ENABLED: 'true'
    DROPCMS_PUBLISH_COMMAND: 'bash /root/publish.sh /live-content ${PRIMARY_LIVE_FQDN}'
    DROPCMS_MEMCACHED_HOST: memcached
    DROPCMS_MEMCACHED_PREFIX: 'preview.'
  volumes:
    - ${PREVIEW_CONTENT_HOST_PATH}:/preview-content
    - drop-cms-live-content:/live-content
  links:
    - memcached
  labels:
    io.rancher.container.pull_image: always
drop-cms-live: # live content
  image: ${DROP_CMS_IMAGE_NAME}
  environment:
    DROPCMS_ROOTDIR: /live-content
    DROPCMS_MEMCACHED_HOST: memcached
    DROPCMS_MEMCACHED_PREFIX: 'live.'
  volumes:
    - ${LIVE_CONTENT_VOLUME_NAME}:/live-content
  links:
    - memcached
  labels:
    io.rancher.container.pull_image: always
cache-warmer: # cache invalidation, no waiting times
  image: helgoboss/wget-cache-warmer
  restart: always
  command: ${PRIMARY_LIVE_FQDN}
  labels:
    io.rancher.container.pull_image: always
memcached: # intra-cms caching
  image: sylvainlasnier/memcached
nginx: # password protection and HTTPS redirection for preview, server/client caching, error pages, domain mapping
  image: helgoboss/drop-cms-nginx
  restart: always
  environment:
    HTPASSWD_PATH: ${HTPASSWD_PATH}
    CERT_PATH: ${CERT_PATH}
    PREVIEW_FQDN: ${PREVIEW_FQDN}
    PRIMARY_LIVE_FQDN: ${PRIMARY_LIVE_FQDN}
    SECONDARY_LIVE_FQDN: ${SECONDARY_LIVE_FQDN}
  volumes:
    - /var/cache/nginx
    - ${NGINX_DATA_HOST_PATH}:/etc/nginx/data
  links:
    - drop-cms-preview
    - drop-cms-live
  labels:
    io.rancher.container.pull_image: always