# As soon as we start using docker-compose 2 syntax, volumes have to be
# specified like this:
#
# volumes:
#   drop-cms-data: {}
drop-cms-preview: # preview content
  image: ${DROP_CMS_IMAGE_NAME}
  environment:
    DROPCMS_ROOTDIR: '/mnt/${RELATIVE_PREVIEW_DATA_PATH}'
    DROPCMS_PUBLISH_ENABLED: 'true'
    DROPCMS_PUBLISH_COMMAND: 'bash /root/publish.sh /mnt/${RELATIVE_LIVE_DATA_PATH} ${PRIMARY_LIVE_FQDN}'
    DROPCMS_MEMCACHED_HOST: memcached
    DROPCMS_MEMCACHED_PREFIX: 'preview.'
  volumes:
    - drop-cms-data:/mnt/${RELATIVE_PREVIEW_DATA_PATH}
    - drop-cms-data:/mnt/${RELATIVE_LIVE_DATA_PATH}
  links:
    - memcached
  labels:
    io.rancher.container.pull_image: always
drop-cms-live: # live content
  image: ${DROP_CMS_IMAGE_NAME}
  environment:
    DROPCMS_ROOTDIR: /mnt/${RELATIVE_LIVE_DATA_PATH}
    DROPCMS_MEMCACHED_HOST: memcached
    DROPCMS_MEMCACHED_PREFIX: 'live.'
  volumes:
    - drop-cms-data:/mnt/${RELATIVE_LIVE_DATA_PATH}
  links:
    - memcached
  labels:
    io.rancher.container.pull_image: always
cache-warmer: # cache invalidation, no waiting times
  image: helgoboss/wget-cache-warmer
  restart: always
  command: ${PRIMARY_LIVE_FQDN}
  labels:
    io.rancher.container.pull_image: always
memcached: # intra-cms caching
  image: sylvainlasnier/memcached
nginx: # password protection and HTTPS redirection for preview, server/client caching, error pages, domain mapping
  image: helgoboss/drop-cms-nginx
  restart: always
  environment:
    HTPASSWD_USER: ${HTPASSWD_USER}
    HTPASSWD_PASSWORD: ${HTPASSWD_PASSWORD}
    PREVIEW_FQDN: ${PREVIEW_FQDN}
    PRIMARY_LIVE_FQDN: ${PRIMARY_LIVE_FQDN}
    SECONDARY_LIVE_FQDN: ${SECONDARY_LIVE_FQDN}
  volumes:
    - /var/cache/nginx
  links:
    - drop-cms-preview
    - drop-cms-live
  labels:
    io.rancher.container.pull_image: always