.catalog:
  name: "Drop CMS"
  version: "v1.0"
  description: "Drop CMS"
  questions:
    - variable: "LIVE_FQDN"
      label: "Live FQDN"
      required: true
      type: "string"
      default: "example.org"
    - variable: "PREVIEW_FQDN"
      label: "Preview FQDN"
      required: true
      type: "string"
      default: "preview.example.org"
    - variable: "HTPASSWD_USER"
      label: "User in .htpasswd"
      required: true
      type: "string"
    - variable: "HTPASSWD_PASSWORD"
      label: "Encrypted password in .htpasswd"
      required: true
      type: "password"
    - variable: "DROPBOX_WWW_DIR"
      label: "WWW directory in Dropbox"
      required: true
      type: "string"
      default: "Apps/example.org/www"