.catalog:
  name: "Drop CMS"
  version: "v1.0"
  description: "Drop CMS"
  questions:
    - variable: "LIVE_FQDN"
      label: "Live FQDN"
      required: true
      type: "string"
      default: "example.org"
    - variable: "RELATIVE_LIVE_DATA_PATH"
      label: "Path to live data (relative to /mnt)"
      required: true
      type: "string"
      default: "drop-cms/live"
    - variable: "PREVIEW_FQDN"
      label: "Preview FQDN"
      required: true
      type: "string"
      default: "preview.example.org"
    - variable: "RELATIVE_PREVIEW_DATA_PATH"
      label: "Path to preview data (relative to /mnt)"
      required: true
      type: "string"
      default: "drop-cms/preview"
    - variable: "HTPASSWD_USER"
      label: "User in .htpasswd"
      required: true
      type: "string"
    - variable: "HTPASSWD_PASSWORD"
      label: "Encrypted password in .htpasswd"
      required: true
      type: "password"