.catalog:
  name: "Drop CMS"
  version: "v1.0"
  description: "Drop CMS"
  questions:
    - variable: "DROP_CMS_IMAGE_NAME"
      label: "Drop CMS image name"
      required: true
      type: "string"
      default: "helgoboss/drop-cms-fs-memcached"
    - variable: "PRIMARY_LIVE_FQDN"
      label: "Primary live FQDN"
      required: true
      type: "string"
      default: "www.example.org"
    - variable: "SECONDARY_LIVE_FQDN"
      label: "Secondary live FQDN (redirected to primary FQDN)"
      required: false
      type: "string"
      default: "example.org"
    - variable: "PREVIEW_FQDN"
      label: "Preview FQDN"
      required: true
      type: "string"
      default: "preview.example.org"
    - variable: "LIVE_CONTENT_VOLUME_NAME"
      label: "Name of the volume containing the live content (/live-content)"
      required: true
      default: "drop-cms-live-content"
      type: "string"
    - variable: "PREVIEW_CONTENT_HOST_PATH"
      label: "Path on host reflecting content for preview (/preview-content)"
      required: true
      default: "/mnt/syncthing/www"
      type: "string"
    - variable: "HTPASSWD_PATH"
      label: "Path to htpasswd file for preview protection"
      required: true
      default: "/etc/nginx/data/htpasswd"
      type: "string"
    - variable: "CERT_PATH"
      label: "Path to certificate (without .key and .crt extension)"
      required: false
      type: "string"
    - variable: "NGINX_DATA_HOST_PATH"
      label: "Path on host reflecting /etc/nginx/data"
      required: true
      default: "/mnt/syncthing/nginx"
      type: "string"