syncthing:
  image: helgoboss/syncthing
  environment:
    REMOTE_DEVICE_ID: ${REMOTE_DEVICE_ID}
    REMOTE_FOLDER_ID: ${REMOTE_FOLDER_ID}
    REMOTE_FOLDER_MOUNT_PATH: /data/${RELATIVE_REMOTE_FOLDER_MOUNT_PATH}
  volumes:
    - /mnt/syncthing:/data
    - /root/.config/syncthing
  restart: always
  ports:
    - "22000:22000"
    - "21027:21027/udp"
  labels:
    io.rancher.container.pull_image: always