.catalog:
  name: "nginx"
  version: "v1.0"
  description: "nginx with flexible configuration"
  questions:
    - variable: "NGINX_DATA_HOST_PATH"
      label: "Path on host reflecting nginx data (/mnt/data)"
      required: true
      type: "string"
      default: "/mnt/syncthing/nginx"